### ISSUE TITLE
Initial LTS releases fail on release.ci

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/release#316]
For some reason, the initial build of LTS releases fail with

> 08:43:25  + utils/release.bash --cloneReleaseGitRepository
> 08:43:25  utils/release.bash: line 536: RELEASE_PROFILE: Release profile required

This can be seen on the jobs for 2.375, 2.361, 2.346 and earlier on release.ci

To start a successful build, you'll need to abort the failing one and restart the job.

**Comment by dduportal** [comment]
My understanding is because of https://github.com/jenkins-infra/release/blob/master/Jenkinsfile.d/core/package#L10.

The directive `parameters` is not parsed during the first build (egg and chicken). I guess we should use a variable in the pipeline to define the env var based on either the default value or the parameters value.

**Comment by daniel-beck** [comment]
See also https://github.com/jenkins-infra/release#staging-before-release-day step "B".
